### PR TITLE
Add return types to match newer Composer versions

### PR DESCRIPTION
**Pull request by DannyTaki**
I just updated the return type of the method `getDistType()` to a string and one other method which PHPStan flagged.  Also checked if some variable were null in `EnvatoApi.php`.  PHPstan is showing no errors up to level 6

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you very much!
This looks very nice.

Could you update Composer version constraint to where `: string` return type was introduced?

**Comment by DannyTaki** [comment]
Haha that was my first real pull request besides documentation edits :). That was fun. Thanks!  I have email configured as my gmail should I be using another email?

**Comment by szepeviktor** [comment]
These two commits are made with your "alliance" email address.

**Comment by DannyTaki** [comment]
Oh that's prollly because I pushed the changes from my work computer. That's fine not a big deal

**Pull request merged**
